# Generated by Django 4.2.25 on 2025-10-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/%Y/%m/%d'),
        ),
    ]
